### ISSUE TITLE
babel.Transformer is not a function

### ISSUE THREAD

**Issue by gkiely** [appfigures/jsx-html-class#2]
I believe this is related to this issue: https://github.com/sindresorhus/ava/issues/207

**Comment by kongakong** [comment]
I encountered the same issue. Here is the stacktrace:

```
ERROR in ./app/scripts/main.js
Module build failed: TypeError: babel.Transformer is not a function
    at module.exports (/Users/antkong/project/node_modules/jsx-html-class/index.js:2:10)
    at Function.memoisePluginContainer (/Users/antkong/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:109:13)
    at Function.normalisePlugin (/Users/antkong/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:142:32)
    at /Users/antkong/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:30
    at Array.map (native)
    at Function.normalisePlugins (/Users/antkong/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:154:20)
    at OptionManager.mergeOptions (/Users/antkong/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:36)
    at OptionManager.init (/Users/antkong/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at File.initOptions (/Users/antkong/project/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/Users/antkong/project/node_modules/babel-core/lib/transformation/file/index.js:139:24)
 @ multi main
webpack: Failed to compile.
```

**Comment by ghost** [comment]
Same error here with a fresh simple React app and presumably also with Apps created with create-react-app (here using class instead of className has no effect).

**Comment by DanielRuf** [comment]
Looks like it is not compatible with babel anymore.

**Comment by oztune** [comment]
We are no longer using this plugin, but PRs are welcome.

**Comment by DanielRuf** [comment]
Weird that the issue is closed but not resolved. Are there actively maintained forks?
